export const userConstants = {
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_FALIURE: "CREATE_USER_FALIURE",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_FALIURE: "LOGIN_USER_FALIURE",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
};

export const detailsConstants = {
  RETRIVE_REQUEST: "RETRIVE_REQUEST",
  RETRIVE_FALIURE: "RETRIVE_FALIURE",
  RETRIVE_SUCCESS: "RETRIVE_SUCCESS",
};

export const appointmentConstants = {
  NEW_APPOINTMENT_REQUEST: "NEW_APPOINTMENT_REQUEST",
  NEW_APPOINTMENT_FALIURE: "NEW_APPOINTMENT_FALIURE",
  NEW_APPOINTMENT_SUCCESS: "NEW_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_REQUEST: "GET_APPOINTMENT_REQUEST",
  GET_APPOINTMENT_FALIURE: "GET_APPOINTMENT_FALIURE",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  DELETE_APPOINTMENT_REQUEST: "DELETE_APPOINTMENT_REQUEST",
  DELETE_APPOINTMENT_FALIURE: "DELETE_APPOINTMENT_FALIURE",
  DELETE_APPOINTMENT_SUCCESS: "DELETE_APPOINTMENT_SUCCESS",
};
